"""add_secrets_and_media_logs_tables

Revision ID: f9f785474ebc
Revises: 92dab02b5b31
Create Date: 2026-08-08 01:26:54.752470

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9f785474ebc'
down_revision: str | None = '92dab02b5b31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'media_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('jellyfin_item_id', sa.String(length=255), nullable=False),
        sa.Column('item_name', sa.String(length=500), nullable=False),
        sa.Column(
            'item_type',
            sa.Enum(
                'MOVIE', 'SERIES', 'AUDIO', 'SEASON', 'EPISODE',
                name='item_type',
            ),
            nullable=False,
        ),
        sa.Column('library_name', sa.String(length=255), nullable=False),
        sa.Column('production_year', sa.Integer(), nullable=True),
        sa.Column(
            'jellyfin_date_created', sa.DateTime(timezone=True), nullable=False,
        ),
        sa.Column(
            'first_seen_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'last_notified_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('notified', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_media_logs_jellyfin_item_id'),
        'media_logs',
        ['jellyfin_item_id'],
        unique=True,
    )
    op.create_table(
        'secrets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'category',
            sa.Enum(
                'SMTP', 'TELEGRAM', 'DISCORD', 'NTFY', 'WEBHOOK',
                'JELLYFIN', 'UNSUBSCRIBE', 'OTHER',
                name='secret_category',
            ),
            nullable=False,
        ),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('encrypted_value', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_secrets_key'), 'secrets', ['key'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secrets_key'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_media_logs_jellyfin_item_id'), table_name='media_logs')
    op.drop_table('media_logs')
    # ### end Alembic commands ###
